export const siteConfig = {
  name: "Life Helpers Initiative",
  shortName: "LHI",
  motto: "Putting a smile on a face — touching lives, transforming households, impacting communities.",
  vision: "A more fulfilled life for everyone.",
  mission:
    "To be a leading non-governmental organization working to maximize all opportunities to empower marginalized people.",
  coreValues: [
    {
      title: "Love",
      description: "Characterized by a friendly atmosphere, kind gestures, and togetherness.",
    },
    {
      title: "Honesty",
      description: "Emphasizing openness, forthrightness, and aligning words with actions.",
    },
    {
      title: "Inclusion",
      description: "Ensuring access for all and providing equal opportunities for staff and clients.",
    },
  ],
  description:
    "Life Helpers Initiative (LHI) is an indigenous Nigerian non-profit established in 2004, advancing health, education, livelihoods, agriculture, and protection for vulnerable communities across 11 states.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://lhinigeria.org",
  foundingDate: "2004-10-01",
  cacRegistration: "CAC/IT/NO 25301 (September 2007)",
  offices: [
    {
      id: "sokoto-hq",
      type: "Headquarters (Sokoto - HQ)",
      name: "Sokoto - HQ",
      address: "Goshen Development Center Tamaje Area Eastern Byepass Road",
      city: "Sokoto",
      state: "Sokoto State",
      country: "Nigeria",
      postalCode: "840001",
      isPrimary: true,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "Goshen Development Center Tamaje Area Eastern Byepass Road Sokoto",
      coordinates: { x: 19, y: 18 }, // SVG percent coords on Nigeria Map
    },
    {
      id: "adamawa-office",
      type: "North-East Field Office (Adamawa)",
      name: "Adamawa Office",
      address: "House 7, Jos Street Off Capital School Damsawo Jimeta",
      city: "Jimeta, Yola",
      state: "Adamawa State",
      country: "Nigeria",
      postalCode: "640284",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "House 7, Jos Street Off Capital School Damsawo Jimeta Adamawa",
      coordinates: { x: 80, y: 55 },
    },
    {
      id: "bauchi-office",
      type: "North-East Field Office (Bauchi & Gombe)",
      name: "Bauchi/Gombe Office",
      address: "Suite 51 Ibrosulada Plaza Opposite Keystone Bank, Bank Road",
      city: "Bauchi",
      state: "Bauchi State",
      country: "Nigeria",
      postalCode: "740241",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "Suite 51 Ibrosulada Plaza Opposite Keystone Bank, Bank Road, Bauchi",
      coordinates: { x: 59, y: 40 },
    },
    {
      id: "kebbi-office",
      type: "North-West Field Office (Kebbi)",
      name: "Kebbi Office",
      address: "Plot: 130 & 131 off Sani Abacha By-pass Behind Leisure City Garden & Event Centre Kawara Area Birnin-Kebbi",
      city: "Birnin-Kebbi",
      state: "Kebbi State",
      country: "Nigeria",
      postalCode: "860241",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "Plot: 130 & 131 off Sani Abacha By-pass Behind Leisure City Garden & Event Centre Kawara Area Birnin-Kebbi, Kebbi State",
      coordinates: { x: 11, y: 28 },
    },
    {
      id: "zamfara-office",
      type: "North-West Field Office (Zamfara)",
      name: "Zamafara Office",
      address: "2nd Floor A.S Mamuda Apartment Opposite Oando Filling station Gusau",
      city: "Gusau",
      state: "Zamfara State",
      country: "Nigeria",
      postalCode: "860221",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "2nd Floor A.S Mamuda Apartment Opposite Oando Filling station Gusau",
      coordinates: { x: 32, y: 26 },
    },
    {
      id: "maiduguri-office",
      type: "North-East Humanitarian Hub (Borno)",
      name: "Maiduguri Office",
      address: "House 12, Gidan Giwa, Sale Kida Street, Close to ICRC, Off Damboa Road",
      city: "Maiduguri",
      state: "Borno State",
      country: "Nigeria",
      postalCode: "600001",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "House 12, Gidan Giwa, Sale Kida Street, Close to ICRC, Off Damboa Road, Maiduguri",
      coordinates: { x: 88, y: 27 },
    },
    {
      id: "yobe-office",
      type: "North-East Field Office (Yobe)",
      name: "Yobe Office",
      address: "House No 157, Usman Adamu Kabarma Street Sabon Fegi, Behind Classi Hotel",
      city: "Damaturu",
      state: "Yobe State",
      country: "Nigeria",
      postalCode: "620101",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "House No 157, Usman Adamu Kabarma Street Sabon Fegi, Behind Classi Hotel Damaturu",
      coordinates: { x: 76, y: 28 },
    },
    {
      id: "ebonyi-office",
      type: "South-East Field Office (Ebonyi)",
      name: "Ebonyi Office",
      address: "Plot 2, Federal Housing Estate, Judges quarters, opposite Isadore Inn",
      city: "Abakaliki",
      state: "Ebonyi State",
      country: "Nigeria",
      postalCode: "480101",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "Plot 2, Federal Housing Estate, Judges quarters, opposite Isadore Inn, Abakaliki",
      coordinates: { x: 48, y: 80 },
    },
    {
      id: "jos-office",
      type: "North-Central Field Office (Plateau)",
      name: "Jos Office",
      address: "Office No 28a Tafawa Balewa Street, opposite United Baptist Church",
      city: "Jos",
      state: "Plateau State",
      country: "Nigeria",
      postalCode: "930101",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "Office No 28a Tafawa Balewa Street, opposite United Baptist Church, Jos",
      coordinates: { x: 52, y: 47 },
    },
    {
      id: "abuja-office",
      type: "Federal Implementation & Liaison Office (FCT)",
      name: "Abuja Office",
      address: "Office lock C, Flat 3. Tail Solarin Crescent Oppositee Zenith Bank. 5th Avenue Gwarimpa",
      city: "Gwarimpa, Abuja",
      state: "Federal Capital Territory",
      country: "Nigeria",
      postalCode: "900108",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "Office lock C, Flat 3. Tail Solarin Crescent Oppositee Zenith Bank. 5th Avenue Gwarimpa",
      coordinates: { x: 38, y: 53 },
    },
    {
      id: "katsina-office",
      type: "North-West Field Office (Katsina)",
      name: "Katsina Office",
      address: "Plot No 14 Bayajidda Road, Along INEC State Office Behind ICPC GRA",
      city: "Katsina",
      state: "Katsina State",
      country: "Nigeria",
      postalCode: "820101",
      isPrimary: false,
      email: "official@lhinigeria.org",
      phone: "+234 901 715 9526",
      mapQuery: "Plot No 14 Bayajidda Road, Along INEC State Office Behind ICPC GRA Katsina",
      coordinates: { x: 42, y: 19 },
    },
  ],
  address: {
    streetAddress: "Goshen Development Center, Tamaje Area, Eastern Byepass Road",
    addressLocality: "Sokoto",
    addressRegion: "Sokoto State",
    postalCode: "840001",
    addressCountry: "NG",
  },
  contact: {
    officialEmail: "official@lhinigeria.org",
    email: "info@lhinigeria.org",
    feedbackEmail: "feedback@lhinigeria.org",
    recruitmentEmail: "recruitment@lhinigeria.org",
    pseaEmail: "psea@lhinigeria.org",
    pseaHotline: "+2349017159526",
    phone: "+2349017159526",
    phoneDisplay: "+234 901 715 9526",
  },
  operationalStates: [
    "Sokoto (Headquarters, 2004)",
    "Kebbi (2013)",
    "Zamfara (2015)",
    "Borno (2017)",
    "Yobe (2017)",
    "Adamawa (2017)",
    "Bauchi (2020)",
    "Ebonyi (2021)",
    "FCT Abuja (Liaison, 2021)",
    "Plateau (2022)",
    "Katsina (2023)",
  ],
};
