export const siteConfig = {
  name: "Life Helpers Initiative",
  shortName: "LHI",
  motto: "Putting a smile on a face — touching lives, transforming households, impacting communities.",
  vision: "A more fulfilled life for everyone.",
  mission:
    "To be a leading non-governmental organization working to maximize all opportunities to empower marginalized people.",
  coreValues: [
    {
      title: "Love",
      description: "Characterized by a friendly atmosphere, kind gestures, and togetherness.",
    },
    {
      title: "Honesty",
      description: "Emphasizing openness, forthrightness, and aligning words with actions.",
    },
    {
      title: "Inclusion",
      description: "Ensuring access for all and providing equal opportunities for staff and clients.",
    },
  ],
  description:
    "Life Helpers Initiative (LHI) is an indigenous Nigerian non-profit established in 2004, advancing health, education, livelihoods, agriculture, and protection for vulnerable communities across 11 states.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://lhinigeria.org",
  foundingDate: "2004-10-01",
  cacRegistration: "CAC/IT/NO 25301 (September 2007)",
  offices: [
    {
      id: "sokoto-hq",
      type: "Headquarters (Sokoto)",
      name: "Goshen Development Center",
      address: "Tamaje Area, Eastern Byepass Road",
      city: "Sokoto",
      state: "Sokoto State",
      country: "Nigeria",
      postalCode: "840001",
      isPrimary: true,
      phone: "+234 901 715 9526",
      mapQuery: "Goshen Development Center, Tamaje Area, Eastern Byepass Road, Sokoto, Nigeria",
    },
    {
      id: "katsina-office",
      type: "North-West Field Office (Katsina)",
      name: "Katsina State Office",
      address: "Plot No 14 Bayajidda Road, Along INEC State Office Behind ICPC GRA",
      city: "Katsina",
      state: "Katsina State",
      country: "Nigeria",
      postalCode: "820101",
      isPrimary: false,
      phone: "+234 901 715 9526",
      mapQuery: "Plot No 14 Bayajidda Road, Along INEC State Office Behind ICPC GRA, Katsina, Nigeria",
    },
    {
      id: "jos-office",
      type: "North-Central Field Office (Jos)",
      name: "Plateau State Office",
      address: "Office No 28a Tafawa Balewa Street, Opposite United Baptist Church",
      city: "Jos",
      state: "Plateau State",
      country: "Nigeria",
      postalCode: "930101",
      isPrimary: false,
      phone: "+234 901 715 9526",
      mapQuery: "Office No 28a Tafawa Balewa Street, Opposite United Baptist Church, Jos, Plateau State, Nigeria",
    },
    {
      id: "bauchi-office",
      type: "North-East Field Office (Bauchi & Gombe)",
      name: "Bauchi / Gombe Regional Office",
      address: "Suite 51 Ibrosulada Plaza Opposite Keystone Bank, Bank Road",
      city: "Bauchi",
      state: "Bauchi State",
      country: "Nigeria",
      postalCode: "740241",
      isPrimary: false,
      phone: "+234 901 715 9526",
      mapQuery: "Suite 51 Ibrosulada Plaza Opposite Keystone Bank, Bank Road, Bauchi, Nigeria",
    },
    {
      id: "maiduguri-office",
      type: "North-East Humanitarian Hub (Maiduguri)",
      name: "Borno Field Office",
      address: "House 12, Gidan Giwa, Sale Kida Street, Close to ICRC, Off Damboa Road",
      city: "Maiduguri",
      state: "Borno State",
      country: "Nigeria",
      postalCode: "600001",
      isPrimary: false,
      phone: "+234 901 715 9526",
      mapQuery: "House 12, Gidan Giwa, Sale Kida Street, Off Damboa Road, Maiduguri, Borno State, Nigeria",
    },
    {
      id: "yobe-office",
      type: "North-East Field Office (Damaturu)",
      name: "Yobe State Office",
      address: "House No 157, Usman Adamu Kabarma Street Sabon Fegi, Behind Classi Hotel",
      city: "Damaturu",
      state: "Yobe State",
      country: "Nigeria",
      postalCode: "620101",
      isPrimary: false,
      phone: "+234 901 715 9526",
      mapQuery: "Usman Adamu Kabarma Street Sabon Fegi, Damaturu, Yobe State, Nigeria",
    },
    {
      id: "abuja-office",
      type: "Federal Implementation & Liaison Office (Abuja)",
      name: "Abuja Liaison Office",
      address: "Office Block C, Flat 3, Tai Solarin Crescent, Opposite Zenith Bank, 5th Avenue Gwarimpa",
      city: "Gwarimpa, Abuja",
      state: "Federal Capital Territory",
      country: "Nigeria",
      postalCode: "900108",
      isPrimary: false,
      phone: "+234 901 715 9526",
      mapQuery: "Tai Solarin Crescent, 5th Avenue Gwarimpa, Abuja, Nigeria",
    },
  ],
  address: {
    streetAddress: "Goshen Development Center, Tamaje Area, Eastern Byepass Road",
    addressLocality: "Sokoto",
    addressRegion: "Sokoto State",
    postalCode: "840001",
    addressCountry: "NG",
  },
  contact: {
    officialEmail: "official@lhinigeria.org",
    email: "info@lhinigeria.org",
    feedbackEmail: "feedback@lhinigeria.org",
    recruitmentEmail: "recruitment@lhinigeria.org",
    phone: "+2349017159526",
    phoneDisplay: "+234 901 715 9526",
  },
  operationalStates: [
    "Sokoto (Headquarters, 2004)",
    "Kebbi (2013)",
    "Zamfara (2015)",
    "Borno (2017)",
    "Yobe (2017)",
    "Adamawa (2017)",
    "Bauchi (2020)",
    "Ebonyi (2021)",
    "FCT Abuja (Liaison, 2021)",
    "Plateau (2022)",
    "Katsina (2023)",
  ],
};
